module clases {
	interface Controlador
	{
		int synchronized unirse(int nhilos);
		string getTrabajo();
		void finTrabajo(string trabajo);
	};
	interface Atacante{
		boolean ready;
		boolean finished;
		String atacar(String usuario,int maxLen);
		String atacarMD5(int inicio,int fin, String md5, int longitud);
		String atacarSHA(int inicio,int fin, String md5, int longitud);
		String getSiguienteCombinacion(String combinacion)
	}
};
