module clases {
	struct Trabajo
	{
		unsigned long id;
		unsigned long tipo;
		string cadena;
		unsigned long puerto;
		string usuario;
		unsigned long tam_maximo;
		unsigned long progress;
		string resultado;
	};
	struct Division
	{
		Trabajo trabajo;
		char c;
	};
	interface Controlador
	{
		typedef sequence <Trabajo> trabajosList;
		attribute trabajosList trabajos;
		const unsigned long MD5=0;
		const unsigned long SHA=1;
		const unsigned long RED=2;
		void finTrabajo(in unsigned long id, in string clave);
		void borrarTrabajo(in unsigned long id);
		Division getDivision();
		Trabajo getTrabajo(in unsigned long id);
		boolean setDivision(in Division t);
		void dividirTrabajo(in Trabajo t);
		Trabajo crearMD5(in string cadena, in unsigned long tam_maximo);
		Trabajo crearSHA(in string cadena, in unsigned long tam_maximo);
		Trabajo crearRed(in string cadena, in unsigned long puerto, in string usuario, in unsigned long tam_maximo);
	};
};
