package clases;


/**
* clases/_ControladorStub.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from interfaz.idl
* jueves 4 de abril de 2013 09H21' CEST
*/

public class _ControladorStub extends org.omg.CORBA.portable.ObjectImpl implements clases.Controlador
{

  public clases.Trabajo[] trabajos ()
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("_get_trabajos", true);
                $in = _invoke ($out);
                clases.Trabajo $result[] = clases.ControladorPackage.trabajosListHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return trabajos (        );
            } finally {
                _releaseReply ($in);
            }
  } // trabajos

  public void trabajos (clases.Trabajo[] newTrabajos)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("_set_trabajos", true);
                clases.ControladorPackage.trabajosListHelper.write ($out, newTrabajos);
                $in = _invoke ($out);
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                trabajos (newTrabajos        );
            } finally {
                _releaseReply ($in);
            }
  } // trabajos

  public void finTrabajo (int id, String clave)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("finTrabajo", true);
                $out.write_ulong (id);
                $out.write_string (clave);
                $in = _invoke ($out);
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                finTrabajo (id, clave        );
            } finally {
                _releaseReply ($in);
            }
  } // finTrabajo

  public void borrarTrabajo (int id)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("borrarTrabajo", true);
                $out.write_ulong (id);
                $in = _invoke ($out);
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                borrarTrabajo (id        );
            } finally {
                _releaseReply ($in);
            }
  } // borrarTrabajo

  public clases.Division getDivision ()
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("getDivision", true);
                $in = _invoke ($out);
                clases.Division $result = clases.DivisionHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return getDivision (        );
            } finally {
                _releaseReply ($in);
            }
  } // getDivision

  public void sumarProgreso (int id, int progress)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("sumarProgreso", true);
                $out.write_ulong (id);
                $out.write_ulong (progress);
                $in = _invoke ($out);
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                sumarProgreso (id, progress        );
            } finally {
                _releaseReply ($in);
            }
  } // sumarProgreso

  public clases.Trabajo getTrabajo (int id)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("getTrabajo", true);
                $out.write_ulong (id);
                $in = _invoke ($out);
                clases.Trabajo $result = clases.TrabajoHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return getTrabajo (id        );
            } finally {
                _releaseReply ($in);
            }
  } // getTrabajo

  public boolean setDivision (clases.Division t)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("setDivision", true);
                clases.DivisionHelper.write ($out, t);
                $in = _invoke ($out);
                boolean $result = $in.read_boolean ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return setDivision (t        );
            } finally {
                _releaseReply ($in);
            }
  } // setDivision

  public void dividirTrabajo (clases.Trabajo t)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("dividirTrabajo", true);
                clases.TrabajoHelper.write ($out, t);
                $in = _invoke ($out);
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                dividirTrabajo (t        );
            } finally {
                _releaseReply ($in);
            }
  } // dividirTrabajo

  public clases.Trabajo crearMD5 (String cadena, int tam_maximo)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("crearMD5", true);
                $out.write_string (cadena);
                $out.write_ulong (tam_maximo);
                $in = _invoke ($out);
                clases.Trabajo $result = clases.TrabajoHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return crearMD5 (cadena, tam_maximo        );
            } finally {
                _releaseReply ($in);
            }
  } // crearMD5

  public clases.Trabajo crearSHA (String cadena, int tam_maximo)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("crearSHA", true);
                $out.write_string (cadena);
                $out.write_ulong (tam_maximo);
                $in = _invoke ($out);
                clases.Trabajo $result = clases.TrabajoHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return crearSHA (cadena, tam_maximo        );
            } finally {
                _releaseReply ($in);
            }
  } // crearSHA

  public clases.Trabajo crearRed (String cadena, int puerto, String usuario, int tam_maximo)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("crearRed", true);
                $out.write_string (cadena);
                $out.write_ulong (puerto);
                $out.write_string (usuario);
                $out.write_ulong (tam_maximo);
                $in = _invoke ($out);
                clases.Trabajo $result = clases.TrabajoHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return crearRed (cadena, puerto, usuario, tam_maximo        );
            } finally {
                _releaseReply ($in);
            }
  } // crearRed

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:clases/Controlador:1.0"};

  public String[] _ids ()
  {
    return (String[])__ids.clone ();
  }

  private void readObject (java.io.ObjectInputStream s) throws java.io.IOException
  {
     String str = s.readUTF ();
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     org.omg.CORBA.Object obj = orb.string_to_object (str);
     org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl) obj)._get_delegate ();
     _set_delegate (delegate);
   } finally {
     orb.destroy() ;
   }
  }

  private void writeObject (java.io.ObjectOutputStream s) throws java.io.IOException
  {
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     String str = orb.object_to_string (this);
     s.writeUTF (str);
   } finally {
     orb.destroy() ;
   }
  }
} // class _ControladorStub
