package clases;


/**
* clases/_ControladorStub.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from interfaz.idl
* miércoles 27 de marzo de 2013 13H37' CET
*/

public class _ControladorStub extends org.omg.CORBA.portable.ObjectImpl implements clases.Controlador
{

  public void finTrabajo (int id, String trabajo)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("finTrabajo", true);
                $out.write_ulong (id);
                $out.write_string (trabajo);
                $in = _invoke ($out);
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                finTrabajo (id, trabajo        );
            } finally {
                _releaseReply ($in);
            }
  } // finTrabajo

  public clases.Division getTrabajo ()
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("getTrabajo", true);
                $in = _invoke ($out);
                clases.Division $result = clases.DivisionHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return getTrabajo (        );
            } finally {
                _releaseReply ($in);
            }
  } // getTrabajo

  public boolean setTrabajo (clases.Division t)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("setTrabajo", true);
                clases.DivisionHelper.write ($out, t);
                $in = _invoke ($out);
                boolean $result = $in.read_boolean ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return setTrabajo (t        );
            } finally {
                _releaseReply ($in);
            }
  } // setTrabajo

  public boolean crearMD5 (String cadena, int tam_maximo)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("crearMD5", true);
                $out.write_string (cadena);
                $out.write_ulong (tam_maximo);
                $in = _invoke ($out);
                boolean $result = $in.read_boolean ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return crearMD5 (cadena, tam_maximo        );
            } finally {
                _releaseReply ($in);
            }
  } // crearMD5

  public boolean crearSHA (String cadena, int tam_maximo)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("crearSHA", true);
                $out.write_string (cadena);
                $out.write_ulong (tam_maximo);
                $in = _invoke ($out);
                boolean $result = $in.read_boolean ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return crearSHA (cadena, tam_maximo        );
            } finally {
                _releaseReply ($in);
            }
  } // crearSHA

  public boolean crearRed (String cadena, int puerto, String usuario, int tam_maximo)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("crearRed", true);
                $out.write_string (cadena);
                $out.write_ulong (puerto);
                $out.write_string (usuario);
                $out.write_ulong (tam_maximo);
                $in = _invoke ($out);
                boolean $result = $in.read_boolean ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return crearRed (cadena, puerto, usuario, tam_maximo        );
            } finally {
                _releaseReply ($in);
            }
  } // crearRed

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:clases/Controlador:1.0"};

  public String[] _ids ()
  {
    return (String[])__ids.clone ();
  }

  private void readObject (java.io.ObjectInputStream s) throws java.io.IOException
  {
     String str = s.readUTF ();
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.Object obj = org.omg.CORBA.ORB.init (args, props).string_to_object (str);
     org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl) obj)._get_delegate ();
     _set_delegate (delegate);
  }

  private void writeObject (java.io.ObjectOutputStream s) throws java.io.IOException
  {
     String[] args = null;
     java.util.Properties props = null;
     String str = org.omg.CORBA.ORB.init (args, props).object_to_string (this);
     s.writeUTF (str);
  }
} // class _ControladorStub
