package clases;

/**
* clases/ControladorHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from interfaz.idl
* miércoles 8 de mayo de 2013 09H08' CEST
*/

public final class ControladorHolder implements org.omg.CORBA.portable.Streamable
{
  /**
 * @uml.property  name="value"
 * @uml.associationEnd  
 */
public clases.Controlador value = null;

  public ControladorHolder ()
  {
  }

  public ControladorHolder (clases.Controlador initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = clases.ControladorHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    clases.ControladorHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return clases.ControladorHelper.type ();
  }

}
