package clases;


/**
* clases/Controlador.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from interfaz.idl
* jueves 4 de abril de 2013 09H21' CEST
*/

public interface Controlador extends ControladorOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
  public static final int MD5 = (int)(0L);
  public static final int SHA = (int)(1L);
  public static final int RED = (int)(2L);
} // interface Controlador
