package clases;


/**
* clases/ControladorOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from interfaz.idl
* martes 23 de abril de 2013 16H45' CEST
*/

public interface ControladorOperations 
{
  clases.Trabajo[] trabajos ();
  void trabajos (clases.Trabajo[] newTrabajos);
  void finTrabajo (int id, String clave);
  void borrarTrabajo (int id);
  clases.Division getDivision ();
  clases.Trabajo getTrabajo (int id);
  boolean setDivision (clases.Division t);
  void dividirTrabajo (clases.Trabajo t);
  clases.Trabajo crearMD5 (String cadena, int tam_maximo, int dic);
  clases.Trabajo crearSHA (String cadena, int tam_maximo, int dic);
  clases.Trabajo crearRed (String cadena, int puerto, String usuario, int tam_maximo, int dic);
} // interface ControladorOperations
