package clases;


/**
* clases/Controlador.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from interfaz.idl
* miércoles 27 de marzo de 2013 13H37' CET
*/

public interface Controlador extends ControladorOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Controlador
