package clases;


/**
* clases/Division.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from interfaz.idl
* jueves 2 de mayo de 2013 11H39' CEST
*/

public final class Division implements org.omg.CORBA.portable.IDLEntity
{
  public clases.Trabajo trabajo = null;
  public char c = (char)0;

  public Division ()
  {
  } // ctor

  public Division (clases.Trabajo _trabajo, char _c)
  {
    trabajo = _trabajo;
    c = _c;
  } // ctor

} // class Division
