package clases;


/**
* clases/Trabajo.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from interfaz.idl
* miércoles 8 de mayo de 2013 09H08' CEST
*/

public final class Trabajo implements org.omg.CORBA.portable.IDLEntity
{
  /**
 * @uml.property  name="borrado"
 */
public boolean borrado = false;
  /**
 * @uml.property  name="id"
 */
public int id = (int)0;
  /**
 * @uml.property  name="tipo"
 */
public int tipo = (int)0;
  /**
 * @uml.property  name="diccionario"
 */
public int diccionario = (int)0;
  /**
 * @uml.property  name="cadena"
 */
public String cadena = null;
  /**
 * @uml.property  name="puerto"
 */
public int puerto = (int)0;
  /**
 * @uml.property  name="usuario"
 */
public String usuario = null;
  /**
 * @uml.property  name="tam_maximo"
 */
public int tam_maximo = (int)0;
  /**
 * @uml.property  name="progress"
 */
public int progress = (int)0;
  /**
 * @uml.property  name="max_progress"
 */
public int max_progress = (int)0;
  /**
 * @uml.property  name="resultado"
 */
public String resultado = null;

  public Trabajo ()
  {
  } // ctor

  public Trabajo (boolean _borrado, int _id, int _tipo, int _diccionario, String _cadena, int _puerto, String _usuario, int _tam_maximo, int _progress, int _max_progress, String _resultado)
  {
    borrado = _borrado;
    id = _id;
    tipo = _tipo;
    diccionario = _diccionario;
    cadena = _cadena;
    puerto = _puerto;
    usuario = _usuario;
    tam_maximo = _tam_maximo;
    progress = _progress;
    max_progress = _max_progress;
    resultado = _resultado;
  } // ctor

} // class Trabajo
