package clases.ControladorPackage;


/**
* clases/ControladorPackage/trabajosListHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from interfaz.idl
* miércoles 8 de mayo de 2013 09H08' CEST
*/

abstract public class trabajosListHelper
{
  private static String  _id = "IDL:clases/Controlador/trabajosList:1.0";

  public static void insert (org.omg.CORBA.Any a, clases.Trabajo[] that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static clases.Trabajo[] extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = clases.TrabajoHelper.type ();
      __typeCode = org.omg.CORBA.ORB.init ().create_sequence_tc (0, __typeCode);
      __typeCode = org.omg.CORBA.ORB.init ().create_alias_tc (clases.ControladorPackage.trabajosListHelper.id (), "trabajosList", __typeCode);
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static clases.Trabajo[] read (org.omg.CORBA.portable.InputStream istream)
  {
    clases.Trabajo value[] = null;
    int _len0 = istream.read_long ();
    value = new clases.Trabajo[_len0];
    for (int _o1 = 0;_o1 < value.length; ++_o1)
      value[_o1] = clases.TrabajoHelper.read (istream);
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, clases.Trabajo[] value)
  {
    ostream.write_long (value.length);
    for (int _i0 = 0;_i0 < value.length; ++_i0)
      clases.TrabajoHelper.write (ostream, value[_i0]);
  }

}
